services:
  db:
    image: ss880/mynewapp1:dbimage
    ports:
      - "3306:3306"
    deploy:
      replicas: 1


  auth_service:
    image: ss880/mynewapp1:authimage
    ports:
      - "5001"
    deploy:
      replicas: 2

  book_service:
    image: ss880/mynewapp1:bookimage
    ports:
      - "5003"
    deploy:
      replicas: 2

  borrow_service:
    image: ss880/mynewapp1:borrowimage
    ports:
      - "5004"
    deploy:
      replicas: 2


  frontend:
    image: ss880/mynewapp1:frontendimage
    ports:
      - "5000"
    deploy:
      replicas: 2
    depends_on:
     - db
     - auth_service
     - book_service
     - borrow_service

    
      











